 steps:
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/the-slate-133223/drupal9:$COMMIT_SHA', '.']
 # Push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/the-slate-133223/drupal9:$COMMIT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - 'drupal9'
   - '--image'
   - 'gcr.io/the-slate-133223/drupal9:$COMMIT_SHA'
   - '--region'
   - 'us-central1'
   - '--platform'
   - 'managed'
   - '--timeout'
   - '1200s'
 images:
 - 'gcr.io/the-slate-133223/drupal9:$COMMIT_SHA'
timeout: 45m
