apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: drupal9
  name: drupal9
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: drupal9
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: drupal9
    spec:
      containers:
        - image: gcr.io/the-slate-133223/github.com/josephtklein/k8s-debian-drupal
          imagePullPolicy: IfNotPresent
          name: k8s-debian-drupal-1
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: drupal9
  name: drupal9-1
  namespace: default
spec:
  maxReplicas: 5
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 80
      type: Resource
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: drupal9
