apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: debian-drupal
    app.kubernetes.io/instance: debian-drupal
    app.kubernetes.io/version: "9.x.x"
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: drupal
  name: debian-drupal
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: debian-drupal
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: debian-drupal
    spec:
      containers:
        - image: gcr.io/the-slate-133223/github.com/josephtklein/k8s-debian-drupal:$REVISION_ID
          imagePullPolicy: IfNotPresent
          name: debian-drupal
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: debian-drupal
  name: debian-drupal
  namespace: default
spec:
  maxReplicas: 5
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 80
      type: Resource
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: debian-drupal
